### ISSUE TITLE
在v2ex上看到了，小白有几个问题想问

### ISSUE THREAD

**Issue by T1anjiu** [hifocus/CleanInStack#1]
问题1 我有海外节点下载的包，md5检验后与你发布的一致，那我可以用它吗，它安全吗？
问题2 你目前这个项目和海外版的包md5不同，是有什么区别吗？
问题3 不是全量包吗，安装时应该是不会连接的，为什么还要屏蔽两个host呀？
问题4 这个屏蔽是一直屏蔽还是说安装完了就好了？
问题5 我也下载了LNMP确定安全的全量包，它在安装时还会连接到别的服务器吗，我也需要作出屏蔽等操作吗？

小白的疑问，希望大佬见谅

**Comment by T1anjiu** [comment]
哦还有一个小问题，在github上面他们的项目我可以去fork他们吗，上面的代码是否有问题？

**Comment by hifocus** [comment]
> 问题1 我有海外节点下载的包，md5检验后与你发布的一致，那我可以用它吗，它安全吗？ 问题2 你目前这个项目和海外版的包md5不同，是有什么区别吗？ 问题3 不是全量包吗，安装时应该是不会连接的，为什么还要屏蔽两个host呀？ 问题4 这个屏蔽是一直屏蔽还是说安装完了就好了？ 问题5 我也下载了LNMP确定安全的全量包，它在安装时还会连接到别的服务器吗，我也需要作出屏蔽等操作吗？
> 
> 小白的疑问，希望大佬见谅

首先这个仓库完全是一个自行承担风险的原则，它并没有透明的源代码和完全的代码审计，没办法保证绝对安全。
Release 里的包取自 Dropbox 平台，*应该*没有被波及到，具体可以参见 https://github.com/oneinstack/oneinstack/issues/487#issuecomment-1529060644 和下面的内容

1. 如果 md5 是一样的，那么文件是一样的，你用它等同于用本项目内的包
2. 不太明白你说 md5 一样又不一样是什么意思
3. 是全量包，理论上也不会连接，屏蔽 hosts 只是预防措施，避免在升级操作的时候遇到可能存在的拉取源服务器的问题（源服务器和整个项目本身已经不可信）
4. 建议全程屏蔽，你不屏蔽也没什么优势
5. 所谓 “确定安全“ 必须最少达到上面的两个标准，我对 LNMP 不熟悉，如果你说的是否会连接恶意服务器，那么需要你自己查看安装包内的所有代码，包括压缩包内的（本次 Oneinstack 的恶意代码就隐藏在 pcre 的压缩包内）；事实上恶意代码还可以用 base64 等方式伪装，所以 ”确保安全“ 不是一个那么简单的概念



> 哦还有一个小问题，在github上面他们的项目我可以去fork他们吗，上面的代码是否有问题？

同样的，自己检查代码，按照我目前的理解（我也不专业），如果 GitHub 上面的项目不连接官方服务器或者其他恶意服务器，那么它应该是安全的，但是这个前提很重要，要自己看代码

**Comment by T1anjiu** [comment]
![Uploading Screenshot_2023-10-07-13-42-45-255_org.mozilla.firefox.jpg…]()
![Uploading Screenshot_2023-10-07-13-43-45-845_org.mozilla.firefox.jpg…]()

**Comment by T1anjiu** [comment]
#恶意包
md5sum oneinstack-full.tar.gz
3dc788dd9feOc13e3db1411e53932331
full.tar.gz
#海外节点包（暂未发现有此问题)
aa55626f6ba9eb8cae2f5a3d9c6c9b96
full.tar.gz
就是你在v2ex上面检测出来的海外节点包的md5和你这个clean版不一样

**Comment by hifocus** [comment]
> #恶意包 md5sum oneinstack-full.tar.gz 3dc788dd9feOc13e3db1411e53932331 full.tar.gz #海外节点包（暂未发现有此问题) aa55626f6ba9eb8cae2f5a3d9c6c9b96 full.tar.gz 就是你在v2ex上面检测出来的海外节点包的md5和你这个clean版不一样

v2 的海外节点包是指在海外节点上下载下来的包和国内的不一样，暂时没有发现有相同的问题
这个仓库里的包是半年前的，详情见我上面提到的 issue
